### ISSUE TITLE
[Python and Hackathon lovers ❤️] Simply write a new example with this tool!

### ISSUE THREAD

**Issue by msramalho** [msramalho/pyhparser#7]
With Pyhparser one can describe _how_ the input data is organized and **automagically** _read it into variables_‼️ 
## Simple instructions for this issue:
 1. Look at the example for [Google Hashcode 2017](https://github.com/msramalho/Pyhparser/blob/master/examples/ex_hashcode2017/ex_hashcode_parser.txt) (code at the bottom)
2. Understand this tool's potential 😁 
3. Try to implement it for [Google Hashcode 2018 edition](https://hashcode.withgoogle.com/2018/tasks/hashcode2018_qualification_task.pdf) **OR**  you can even find your own examples of applications of pyhparser!

#### Here is the code for Hashcode 2017 (Qualification):
```python
#read five integers into variables
(int, nVideos) (int, nEndpoints) (int, nRequests) (int, nCaches) (int, cacheSize)

#list of ints with length equal to nVideos
[list, {nVideos}, (int), videos]

#list of nEndpoints more complex elements (class Endpoint)
[list, {nEndpoints},
    [class, Endpoint,
        {datacenterLatency:(int), countCaches:(int, tempCount), caches:
            [list, {tempCount}, {(int), (int)}]
        }
    ]
, endpoints]

[list, {nRequests},
    [class, Request, {videoId: (int), endpointId: (int), countRequests: (int)}]
, requests]
```

**Comment by son-vyas** [comment]
Can I give it a try?

**Comment by msramalho** [comment]
Yeah, sure, I welcome feedback on the tool and people looking to try it out!

You can see the whole example for 2017 [here](https://github.com/msramalho/Pyhparser/tree/master/examples/ex_hashcode2017). It contains:
 * the 4 different input files that google gives participants
* the pdf with the problem description
* the [parser text](https://github.com/msramalho/Pyhparser/blob/master/examples/ex_hashcode2017/ex_hashcode_parser.txt) like the example above
* the [parser script](https://github.com/msramalho/Pyhparser/blob/master/examples/ex_hashcode2017/ex_hashcode_script.py) if you need to define new python classes

Good Luck 😄
